package otyacraft.items;

import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.init.Blocks;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.Item;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.GameRegistry.ObjectHolder;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import net.minecraftforge.registries.IForgeRegistry;
import otyacraft.Variable;
import otyacraft.blocks.OCblocks;
@ObjectHolder(Variable.MODID)
public class OCitems {
	//Item Declaration アイテム宣言
    public static final Item TEST = new Item_test();
    public static final Item SECOND_GRILLED_BRICK = new Item_second_grilled_brick();
    public static final Item COPPER_INGOT = new Item_ingot("copper");
    public static final Item TIN_INGOT = new Item_ingot("tin");
    public static final Item LEAD_INGOT = new Item_ingot("lead");
    public static final Item NICKEL_INGOT = new Item_ingot("nickel");
    public static final Item SILVER_INGOT = new Item_ingot("silver");
    public static final Item RUBY = new Item_gem("ruby");
    public static final Item SAPPHIRE = new Item_gem("sapphire");
    public static final Item PERMAFROST_INGOT = new Item_ingot("permafrost");
    public static final Item CENTERL_INGOT = new Item_ingot("centerl");
    public static final Item FICTNIUM_INGOT = new Item_ingot("fictnium");
    public static final Item REALITE = new Item_gem("realite");
    public static final Item COPPER_NUGGET = new Item_nugget("copper");
    public static final Item TIN_NUGGET = new Item_nugget("tin");
    public static final Item LEAD_NUGGET = new Item_nugget("lead");
    public static final Item NICKEL_NUGGET = new Item_nugget("nickel");
    public static final Item SILVER_NUGGET = new Item_nugget("silver");
    public static final Item CENTERL_NUGGET = new Item_nugget("centerl");
    public static final Item IRON_GEAR = new Item_gear("iron");
    public static final Item COPPER_GEAR = new Item_gear("copper");
    public static final Item TIN_GEAR = new Item_gear("tin");
    public static final Item LEAD_GEAR = new Item_gear("lead");
    public static final Item NICKEL_GEAR = new Item_gear("nickel");
    public static final Item CENTERL_GEAR = new Item_gear("centerl");
    public static final Item SILVER_GEAR = new Item_gear("silver");
    public static final Item PERMAFROST_POWDER = new Item_oc_nomal("permafrost_powder","permafrostpowder");
    public static final Item TEA_LEAVES = new Item_oc_nomal("tea_leaves","tealeaves");
    public static final Item TEA_CUP = new Item_oc_nomal("tea_cup","teacup");
    public static final Item TEA_LEAVES_POWDER = new Item_oc_nomal("tea_leaves_powder","tealeavespowder");
    public static final Item NEEDLE = new Item_needle();
    public static final Item BROKEN_NEEDLE = new Item_oc_unused("broken_needle","brokenneedle");
    public static final Item OTYACRFT_DICTIONARY = new Item_oc_dictionary();
    public static final Item TEA_AND_TEA_CUP = new Item_tea_and_tea_cup(4, 0.3F, false,"tea_and_tea_cup","teaandteacup");
    public static final Item SILVER_APPLE = new Item_silver_apple(4, 0.3F, false);
    public static final Item TEA_SEED = new Item_seed(OCblocks.TEA_CROP,Blocks.FARMLAND,"tea");
    public static final Item TEA_FLOWER = new Item_oc_nomal("tea_flower","teaflower");
    public static final Item RADEON = new Item_oc_radeon("radeon");
    //Tool and Armor ツールと装備
    public static final Item SECOND_GRILLED_BRICK_SWORD = new Item_oc_nomal_sword("sgb",OCToolMaterial.SGB);
    public static final Item SECOND_GRILLED_BRICK_SHOVEL = new Item_oc_nomal_shovel("sgb",OCToolMaterial.SGB);
    public static final Item SECOND_GRILLED_BRICK_PICKAXE = new Item_oc_nomal_pickaxe("sgb",OCToolMaterial.SGB);
    public static final Item SECOND_GRILLED_BRICK_AXE = new Item_oc_nomal_axe("sgb",OCToolMaterial.SGB, 8.0F, -3.2F);
    public static final Item SECOND_GRILLED_BRICK_HOE = new Item_oc_nomal_hoe("sgb",OCToolMaterial.SGB);
    public static final Item SECOND_GRILLED_BRICK_HELMET = new Item_oc_nomal_armor("sgbhelmet","sgb_helmet",OCToolMaterial.SGB_A,1,EntityEquipmentSlot.HEAD);
    public static final Item SECOND_GRILLED_BRICK_CHESTPLATE = new Item_oc_nomal_armor("sgbchestplate","sgb_chestplate",OCToolMaterial.SGB_A,1,EntityEquipmentSlot.CHEST);
    public static final Item SECOND_GRILLED_BRICK_LEGGINGS = new Item_oc_nomal_armor("sgbleggings","sgb_leggings",OCToolMaterial.SGB_A,2,EntityEquipmentSlot.LEGS);
    public static final Item SECOND_GRILLED_BRICK_BOOTS = new Item_oc_nomal_armor("sgbboots","sgb_boots",OCToolMaterial.SGB_A,1,EntityEquipmentSlot.FEET);
    public static final Item COPPER_SWORD = new Item_oc_nomal_sword("copper",OCToolMaterial.copper);
    public static final Item COPPER_SHOVEL = new Item_oc_nomal_shovel("copper",OCToolMaterial.copper);
    public static final Item COPPER_PICKAXE = new Item_oc_nomal_pickaxe("copper",OCToolMaterial.copper);
    public static final Item COPPER_AXE = new Item_oc_nomal_axe("copper",OCToolMaterial.copper, 8.0F, -3.1F);
    public static final Item COPPER_HOE = new Item_oc_nomal_hoe("copper",OCToolMaterial.copper);
    public static final Item COPPER_HELMET = new Item_oc_nomal_armor("copperhelmet","copper_helmet",OCToolMaterial.copper_A,1,EntityEquipmentSlot.HEAD);
    public static final Item COPPER_CHESTPLATE = new Item_oc_nomal_armor("copperchestplate","copper_chestplate",OCToolMaterial.copper_A,1,EntityEquipmentSlot.CHEST);
    public static final Item COPPER_LEGGINGS = new Item_oc_nomal_armor("copperleggings","copper_leggings",OCToolMaterial.copper_A,2,EntityEquipmentSlot.LEGS);
    public static final Item COPPER_BOOTS = new Item_oc_nomal_armor("copperboots","copper_boots",OCToolMaterial.copper_A,1,EntityEquipmentSlot.FEET);
    public static final Item TIN_SWORD = new Item_oc_nomal_sword("tin",OCToolMaterial.tin);
    public static final Item TIN_SHOVEL = new Item_oc_nomal_shovel("tin",OCToolMaterial.tin);
    public static final Item TIN_PICKAXE = new Item_oc_nomal_pickaxe("tin",OCToolMaterial.tin);
    public static final Item TIN_AXE = new Item_oc_nomal_axe("tin",OCToolMaterial.tin, 8.0F, -3.1F);
    public static final Item TIN_HOE = new Item_oc_nomal_hoe("tin",OCToolMaterial.tin);
    public static final Item TIN_HELMET = new Item_oc_nomal_armor("tinhelmet","tin_helmet",OCToolMaterial.tin_A,1,EntityEquipmentSlot.HEAD);
    public static final Item TIN_CHESTPLATE = new Item_oc_nomal_armor("tinchestplate","tin_chestplate",OCToolMaterial.tin_A,1,EntityEquipmentSlot.CHEST);
    public static final Item TIN_LEGGINGS = new Item_oc_nomal_armor("tinleggings","tin_leggings",OCToolMaterial.tin_A,2,EntityEquipmentSlot.LEGS);
    public static final Item TIN_BOOTS = new Item_oc_nomal_armor("tinboots","tin_boots",OCToolMaterial.tin_A,1,EntityEquipmentSlot.FEET);
    public static final Item LEAD_SWORD = new Item_oc_nomal_sword("lead",OCToolMaterial.lead);
    public static final Item LEAD_SHOVEL = new Item_oc_nomal_shovel("lead",OCToolMaterial.lead);
    public static final Item LEAD_PICKAXE = new Item_oc_nomal_pickaxe("lead",OCToolMaterial.lead);
    public static final Item LEAD_AXE = new Item_oc_nomal_axe("lead",OCToolMaterial.lead, 8.0F, -3.1F);
    public static final Item LEAD_HOE = new Item_oc_nomal_hoe("lead",OCToolMaterial.lead);
    public static final Item LEAD_HELMET = new Item_oc_nomal_armor("leadhelmet","lead_helmet",OCToolMaterial.lead_A,1,EntityEquipmentSlot.HEAD);
    public static final Item LEAD_CHESTPLATE = new Item_oc_nomal_armor("leadchestplate","lead_chestplate",OCToolMaterial.lead_A,1,EntityEquipmentSlot.CHEST);
    public static final Item LEAD_LEGGINGS = new Item_oc_nomal_armor("leadleggings","lead_leggings",OCToolMaterial.lead_A,2,EntityEquipmentSlot.LEGS);
    public static final Item LEAD_BOOTS = new Item_oc_nomal_armor("leadboots","lead_boots",OCToolMaterial.lead_A,1,EntityEquipmentSlot.FEET);
    public static final Item NICKEL_SWORD = new Item_oc_nomal_sword("nickel",OCToolMaterial.nickel);
    public static final Item NICKEL_SHOVEL = new Item_oc_nomal_shovel("nickel",OCToolMaterial.nickel);
    public static final Item NICKEL_PICKAXE = new Item_oc_nomal_pickaxe("nickel",OCToolMaterial.nickel);
    public static final Item NICKEL_AXE = new Item_oc_nomal_axe("nickel",OCToolMaterial.nickel, 8.0F, -3.1F);
    public static final Item NICKEL_HOE = new Item_oc_nomal_hoe("nickel",OCToolMaterial.nickel);
    public static final Item NICKEL_HELMET = new Item_oc_nomal_armor("nickelhelmet","nickel_helmet",OCToolMaterial.nickel_A,1,EntityEquipmentSlot.HEAD);
    public static final Item NICKEL_CHESTPLATE = new Item_oc_nomal_armor("nickelchestplate","nickel_chestplate",OCToolMaterial.nickel_A,1,EntityEquipmentSlot.CHEST);
    public static final Item NICKEL_LEGGINGS = new Item_oc_nomal_armor("nickelleggings","nickel_leggings",OCToolMaterial.nickel_A,2,EntityEquipmentSlot.LEGS);
    public static final Item NICKEL_BOOTS = new Item_oc_nomal_armor("nickelboots","nickel_boots",OCToolMaterial.nickel_A,1,EntityEquipmentSlot.FEET);
    public static final Item RUBY_SWORD = new Item_oc_nomal_sword("ruby",OCToolMaterial.ruby);
    public static final Item RUBY_SHOVEL = new Item_oc_nomal_shovel("ruby",OCToolMaterial.ruby);
    public static final Item RUBY_PICKAXE = new Item_oc_nomal_pickaxe("ruby",OCToolMaterial.ruby);
    public static final Item RUBY_AXE = new Item_oc_nomal_axe("ruby",OCToolMaterial.ruby, 8.0F, -3.0F);
    public static final Item RUBY_HOE = new Item_oc_nomal_hoe("ruby",OCToolMaterial.ruby);
    public static final Item RUBY_HELMET = new Item_oc_nomal_armor("rubyhelmet","ruby_helmet",OCToolMaterial.ruby_A,1,EntityEquipmentSlot.HEAD);
    public static final Item RUBY_CHESTPLATE = new Item_oc_nomal_armor("rubychestplate","ruby_chestplate",OCToolMaterial.ruby_A,1,EntityEquipmentSlot.CHEST);
    public static final Item RUBY_LEGGINGS = new Item_oc_nomal_armor("rubyleggings","ruby_leggings",OCToolMaterial.ruby_A,2,EntityEquipmentSlot.LEGS);
    public static final Item RUBY_BOOTS = new Item_oc_nomal_armor("rubyboots","ruby_boots",OCToolMaterial.ruby_A,1,EntityEquipmentSlot.FEET);
    public static final Item SAPPHIRE_SWORD = new Item_oc_nomal_sword("sapphire",OCToolMaterial.sapphire);
    public static final Item SAPPHIRE_SHOVEL = new Item_oc_nomal_shovel("sapphire",OCToolMaterial.sapphire);
    public static final Item SAPPHIRE_PICKAXE = new Item_oc_nomal_pickaxe("sapphire",OCToolMaterial.sapphire);
    public static final Item SAPPHIRE_AXE = new Item_oc_nomal_axe("sapphire",OCToolMaterial.sapphire, 8.0F, -3.0F);
    public static final Item SAPPHIRE_HOE = new Item_oc_nomal_hoe("sapphire",OCToolMaterial.sapphire);
    public static final Item SAPPHIRE_HELMET = new Item_oc_nomal_armor("sapphirehelmet","sapphire_helmet",OCToolMaterial.sapphire_A,1,EntityEquipmentSlot.HEAD);
    public static final Item SAPPHIRE_CHESTPLATE = new Item_oc_nomal_armor("sapphirechestplate","sapphire_chestplate",OCToolMaterial.sapphire_A,1,EntityEquipmentSlot.CHEST);
    public static final Item SAPPHIRE_LEGGINGS = new Item_oc_nomal_armor("sapphireleggings","sapphire_leggings",OCToolMaterial.sapphire_A,2,EntityEquipmentSlot.LEGS);
    public static final Item SAPPHIRE_BOOTS = new Item_oc_nomal_armor("sapphireboots","sapphire_boots",OCToolMaterial.sapphire_A,1,EntityEquipmentSlot.FEET);
    public static final Item SILVER_SWORD = new Item_oc_nomal_sword("silver",OCToolMaterial.silver);
    public static final Item SILVER_SHOVEL = new Item_oc_nomal_shovel("silver",OCToolMaterial.silver);
    public static final Item SILVER_PICKAXE = new Item_oc_nomal_pickaxe("silver",OCToolMaterial.silver);
    public static final Item SILVER_AXE = new Item_oc_nomal_axe("silver",OCToolMaterial.silver, 6.0F, -3.0F);
    public static final Item SILVER_HOE = new Item_oc_nomal_hoe("silver",OCToolMaterial.silver);
    public static final Item SILVER_HELMET = new Item_oc_nomal_armor("silverhelmet","silver_helmet",OCToolMaterial.silver_A,1,EntityEquipmentSlot.HEAD);
    public static final Item SILVER_CHESTPLATE = new Item_oc_nomal_armor("silverchestplate","silver_chestplate",OCToolMaterial.silver_A,1,EntityEquipmentSlot.CHEST);
    public static final Item SILVER_LEGGINGS = new Item_oc_nomal_armor("silverleggings","silver_leggings",OCToolMaterial.silver_A,2,EntityEquipmentSlot.LEGS);
    public static final Item SILVER_BOOTS = new Item_oc_nomal_armor("silverboots","silver_boots",OCToolMaterial.silver_A,1,EntityEquipmentSlot.FEET);
    public static final Item CENTERL_SWORD = new Item_oc_nomal_sword("centerl",OCToolMaterial.centerl);
    public static final Item CENTERL_SHOVEL = new Item_oc_nomal_shovel("centerl",OCToolMaterial.centerl);
    public static final Item CENTERL_PICKAXE = new Item_oc_nomal_pickaxe("centerl",OCToolMaterial.centerl);
    public static final Item CENTERL_AXE = new Item_oc_nomal_axe("centerl",OCToolMaterial.centerl, 8.0F, -3.1F);
    public static final Item CENTERL_HOE = new Item_oc_nomal_hoe("centerl",OCToolMaterial.centerl);
    public static final Item CENTERL_HELMET = new Item_oc_nomal_armor("centerlhelmet","centerl_helmet",OCToolMaterial.centerl_A,1,EntityEquipmentSlot.HEAD);
    public static final Item CENTERL_CHESTPLATE = new Item_oc_nomal_armor("centerlchestplate","centerl_chestplate",OCToolMaterial.centerl_A,1,EntityEquipmentSlot.CHEST);
    public static final Item CENTERL_LEGGINGS = new Item_oc_nomal_armor("centerlleggings","centerl_leggings",OCToolMaterial.centerl_A,2,EntityEquipmentSlot.LEGS);
    public static final Item CENTERL_BOOTS = new Item_oc_nomal_armor("centerlboots","centerl_boots",OCToolMaterial.centerl_A,1,EntityEquipmentSlot.FEET);
    public static final Item PERMAFROST_SWORD = new Item_oc_nomal_sword("permafrost",OCToolMaterial.permafrost);
    public static final Item PERMAFROST_SHOVEL = new Item_oc_nomal_shovel("permafrost",OCToolMaterial.permafrost);
    public static final Item PERMAFROST_PICKAXE = new Item_oc_nomal_pickaxe("permafrost",OCToolMaterial.permafrost);
    public static final Item PERMAFROST_AXE = new Item_oc_nomal_axe("permafrost",OCToolMaterial.permafrost, 9.0F, -2.5F);
    public static final Item PERMAFROST_HOE = new Item_oc_nomal_hoe("permafrost",OCToolMaterial.permafrost);
    public static final Item PERMAFROST_HELMET = new Item_oc_nomal_armor("permafrosthelmet","permafrost_helmet",OCToolMaterial.permafrost_A,1,EntityEquipmentSlot.HEAD);
    public static final Item PERMAFROST_CHESTPLATE = new Item_oc_nomal_armor("permafrostchestplate","permafrost_chestplate",OCToolMaterial.permafrost_A,1,EntityEquipmentSlot.CHEST);
    public static final Item PERMAFROST_LEGGINGS = new Item_oc_nomal_armor("permafrostleggings","permafrost_leggings",OCToolMaterial.permafrost_A,2,EntityEquipmentSlot.LEGS);
    public static final Item PERMAFROST_BOOTS = new Item_oc_nomal_armor("permafrostboots","permafrost_boots",OCToolMaterial.permafrost_A,1,EntityEquipmentSlot.FEET);
    public static final Item REFI_SWORD = new Item_REFI_sword();
    @SubscribeEvent
    public static void registerItem(IForgeRegistry<Item> items) {
    	//Item register アイテム登録
       items.register(TEST);
       items.register(SECOND_GRILLED_BRICK);
       items.register(COPPER_INGOT);
       items.register(TIN_INGOT);
       items.register(LEAD_INGOT);
       items.register(NICKEL_INGOT);
       items.register(SILVER_INGOT);
       items.register(RUBY);
       items.register(SAPPHIRE);
       items.register(PERMAFROST_INGOT);
       items.register(CENTERL_INGOT);
       items.register(FICTNIUM_INGOT);
       items.register(REALITE);
       items.register(COPPER_NUGGET);
       items.register(TIN_NUGGET);
       items.register(LEAD_NUGGET);
       items.register(NICKEL_NUGGET);
       items.register(SILVER_NUGGET);
       items.register(CENTERL_NUGGET);
       items.register(IRON_GEAR);
       items.register(COPPER_GEAR);
       items.register(TIN_GEAR);
       items.register(LEAD_GEAR);
       items.register(NICKEL_GEAR);
       items.register(CENTERL_GEAR);
       items.register(SILVER_GEAR);
       items.register(PERMAFROST_POWDER);
       items.register(TEA_LEAVES);
       items.register(TEA_CUP);
       items.register(TEA_LEAVES_POWDER);
       items.register(NEEDLE);
       items.register(BROKEN_NEEDLE);
       items.register(OTYACRFT_DICTIONARY);
       items.register(TEA_AND_TEA_CUP);
       items.register(SILVER_APPLE);
       items.register(TEA_SEED);
       items.register(TEA_FLOWER);
       items.register(RADEON);
       items.register(SECOND_GRILLED_BRICK_SWORD);
       items.register(SECOND_GRILLED_BRICK_SHOVEL);
       items.register(SECOND_GRILLED_BRICK_PICKAXE);
       items.register(SECOND_GRILLED_BRICK_AXE);
       items.register(SECOND_GRILLED_BRICK_HOE);
       items.register(SECOND_GRILLED_BRICK_HELMET);
       items.register(SECOND_GRILLED_BRICK_CHESTPLATE);
       items.register(SECOND_GRILLED_BRICK_LEGGINGS);
       items.register(SECOND_GRILLED_BRICK_BOOTS);
       items.register(COPPER_SWORD);
       items.register(COPPER_SHOVEL);
       items.register(COPPER_PICKAXE);
       items.register(COPPER_AXE);
       items.register(COPPER_HOE);
       items.register(COPPER_HELMET);
       items.register(COPPER_CHESTPLATE);
       items.register(COPPER_LEGGINGS);
       items.register(COPPER_BOOTS);
       items.register(TIN_SWORD);
       items.register(TIN_SHOVEL);
       items.register(TIN_PICKAXE);
       items.register(TIN_AXE);
       items.register(TIN_HOE);
       items.register(TIN_HELMET);
       items.register(TIN_CHESTPLATE);
       items.register(TIN_LEGGINGS);
       items.register(TIN_BOOTS);
       items.register(LEAD_SWORD);
       items.register(LEAD_SHOVEL);
       items.register(LEAD_PICKAXE);
       items.register(LEAD_AXE);
       items.register(LEAD_HOE);
       items.register(LEAD_HELMET);
       items.register(LEAD_CHESTPLATE);
       items.register(LEAD_LEGGINGS);
       items.register(LEAD_BOOTS);
       items.register(NICKEL_SWORD);
       items.register(NICKEL_SHOVEL);
       items.register(NICKEL_PICKAXE);
       items.register(NICKEL_AXE);
       items.register(NICKEL_HOE);
       items.register(NICKEL_HELMET);
       items.register(NICKEL_CHESTPLATE);
       items.register(NICKEL_LEGGINGS);
       items.register(NICKEL_BOOTS);
       items.register(RUBY_SWORD);
       items.register(RUBY_SHOVEL);
       items.register(RUBY_PICKAXE);
       items.register(RUBY_AXE);
       items.register(RUBY_HOE);
       items.register(RUBY_HELMET);
       items.register(RUBY_CHESTPLATE);
       items.register(RUBY_LEGGINGS);
       items.register(RUBY_BOOTS);
       items.register(SAPPHIRE_SWORD);
       items.register(SAPPHIRE_SHOVEL);
       items.register(SAPPHIRE_PICKAXE);
       items.register(SAPPHIRE_AXE);
       items.register(SAPPHIRE_HOE);
       items.register(SAPPHIRE_HELMET);
       items.register(SAPPHIRE_CHESTPLATE);
       items.register(SAPPHIRE_LEGGINGS);
       items.register(SAPPHIRE_BOOTS);
       items.register(SILVER_SWORD);
       items.register(SILVER_SHOVEL);
       items.register(SILVER_PICKAXE);
       items.register(SILVER_AXE);
       items.register(SILVER_HOE);
       items.register(SILVER_HELMET);
       items.register(SILVER_CHESTPLATE);
       items.register(SILVER_LEGGINGS);
       items.register(SILVER_BOOTS);
       items.register(CENTERL_SWORD);
       items.register(CENTERL_SHOVEL);
       items.register(CENTERL_PICKAXE);
       items.register(CENTERL_AXE);
       items.register(CENTERL_HOE);
       items.register(CENTERL_HELMET);
       items.register(CENTERL_CHESTPLATE);
       items.register(CENTERL_LEGGINGS);
       items.register(CENTERL_BOOTS);
       items.register(PERMAFROST_SWORD);
       items.register(PERMAFROST_SHOVEL);
       items.register(PERMAFROST_PICKAXE);
       items.register(PERMAFROST_AXE);
       items.register(PERMAFROST_HOE);
       items.register(PERMAFROST_HELMET);
       items.register(PERMAFROST_CHESTPLATE);
       items.register(PERMAFROST_LEGGINGS);
       items.register(PERMAFROST_BOOTS);
       items.register(REFI_SWORD);
    }

    @SubscribeEvent
    @SideOnly(Side.CLIENT)
    public static void tourokuModels(){
    	ModelLoader.setCustomModelResourceLocation(TEST, 0,new net.minecraft.client.renderer.block.model.ModelResourceLocation(new ResourceLocation(Variable.MODID, "test_item"), "inventory"));

        ModelLoader.setCustomModelResourceLocation(SECOND_GRILLED_BRICK, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "second_grilled_brick"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(COPPER_INGOT, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "copper_ingot"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TIN_INGOT, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tin_ingot"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(LEAD_INGOT, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "lead_ingot"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(NICKEL_INGOT, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "nickel_ingot"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SILVER_INGOT, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "silver_ingot"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(RUBY, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "ruby"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SAPPHIRE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "sapphire"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(PERMAFROST_INGOT, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "permafrost_ingot"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(CENTERL_INGOT, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "centerl_ingot"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(FICTNIUM_INGOT, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "fictnium_ingot"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(REALITE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "realite"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(COPPER_NUGGET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "copper_nugget"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TIN_NUGGET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tin_nugget"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(LEAD_NUGGET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "lead_nugget"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(NICKEL_NUGGET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "nickel_nugget"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SILVER_NUGGET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "silver_nugget"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(CENTERL_NUGGET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "centerl_nugget"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(IRON_GEAR, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "iron_gear"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(COPPER_GEAR, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "copper_gear"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(LEAD_GEAR, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "lead_gear"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(NICKEL_GEAR, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "nickel_gear"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(CENTERL_GEAR, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "centerl_gear"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SILVER_GEAR, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "silver_gear"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TIN_GEAR, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tin_gear"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(PERMAFROST_POWDER, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "permafrost_powder"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TEA_LEAVES, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tea_leaves"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TEA_CUP, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tea_cup"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TEA_LEAVES_POWDER, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tea_leaves_powder"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(BROKEN_NEEDLE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "broken_needle"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(NEEDLE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "needle"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(OTYACRFT_DICTIONARY, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "oc_dictionary"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TEA_AND_TEA_CUP, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tea_and_tea_cup"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SILVER_APPLE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "silver_apple"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SECOND_GRILLED_BRICK_SWORD, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "second_grilled_brick_sword"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SECOND_GRILLED_BRICK_SHOVEL, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "second_grilled_brick_shovel"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SECOND_GRILLED_BRICK_PICKAXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "second_grilled_brick_pickaxe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SECOND_GRILLED_BRICK_AXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "second_grilled_brick_axe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SECOND_GRILLED_BRICK_HOE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "second_grilled_brick_hoe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SECOND_GRILLED_BRICK_HELMET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "second_grilled_brick_helmet"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SECOND_GRILLED_BRICK_CHESTPLATE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "second_grilled_brick_chestplate"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SECOND_GRILLED_BRICK_LEGGINGS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "second_grilled_brick_leggings"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SECOND_GRILLED_BRICK_BOOTS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "second_grilled_brick_boots"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(COPPER_SWORD, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "copper_sword"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(COPPER_SHOVEL, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "copper_shovel"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(COPPER_PICKAXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "copper_pickaxe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(COPPER_AXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "copper_axe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(COPPER_HOE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "copper_hoe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(COPPER_HELMET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "copper_helmet"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(COPPER_CHESTPLATE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "copper_chestplate"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(COPPER_LEGGINGS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "copper_leggings"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(COPPER_BOOTS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "copper_boots"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TIN_SWORD, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tin_sword"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TIN_SHOVEL, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tin_shovel"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TIN_PICKAXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tin_pickaxe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TIN_AXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tin_axe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TIN_HOE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tin_hoe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TIN_HELMET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tin_helmet"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TIN_CHESTPLATE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tin_chestplate"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TIN_LEGGINGS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tin_leggings"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TIN_BOOTS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tin_boots"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(LEAD_SWORD, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "lead_sword"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(LEAD_SHOVEL, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "lead_shovel"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(LEAD_PICKAXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "lead_pickaxe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(LEAD_AXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "lead_axe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(LEAD_HOE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "lead_hoe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(LEAD_HELMET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "lead_helmet"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(LEAD_CHESTPLATE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "lead_chestplate"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(LEAD_LEGGINGS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "lead_leggings"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(LEAD_BOOTS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "lead_boots"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(NICKEL_SWORD, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "nickel_sword"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(NICKEL_SHOVEL, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "nickel_shovel"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(NICKEL_PICKAXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "nickel_pickaxe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(NICKEL_AXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "nickel_axe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(NICKEL_HOE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "nickel_hoe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(NICKEL_HELMET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "nickel_helmet"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(NICKEL_CHESTPLATE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "nickel_chestplate"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(NICKEL_LEGGINGS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "nickel_leggings"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(NICKEL_BOOTS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "nickel_boots"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(RUBY_SWORD, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "ruby_sword"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(RUBY_SHOVEL, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "ruby_shovel"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(RUBY_PICKAXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "ruby_pickaxe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(RUBY_AXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "ruby_axe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(RUBY_HOE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "ruby_hoe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(RUBY_HELMET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "ruby_helmet"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(RUBY_CHESTPLATE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "ruby_chestplate"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(RUBY_LEGGINGS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "ruby_leggings"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(RUBY_BOOTS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "ruby_boots"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SAPPHIRE_SWORD, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "sapphire_sword"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SAPPHIRE_SHOVEL, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "sapphire_shovel"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SAPPHIRE_PICKAXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "sapphire_pickaxe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SAPPHIRE_AXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "sapphire_axe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SAPPHIRE_HOE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "sapphire_hoe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SAPPHIRE_HELMET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "sapphire_helmet"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SAPPHIRE_CHESTPLATE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "sapphire_chestplate"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SAPPHIRE_LEGGINGS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "sapphire_leggings"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SAPPHIRE_BOOTS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "sapphire_boots"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SILVER_SWORD, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "silver_sword"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SILVER_SHOVEL, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "silver_shovel"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SILVER_PICKAXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "silver_pickaxe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SILVER_AXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "silver_axe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SILVER_HOE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "silver_hoe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SILVER_HELMET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "silver_helmet"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SILVER_CHESTPLATE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "silver_chestplate"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SILVER_LEGGINGS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "silver_leggings"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SILVER_BOOTS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "silver_boots"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(CENTERL_SWORD, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "centerl_sword"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(CENTERL_SHOVEL, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "centerl_shovel"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(CENTERL_PICKAXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "centerl_pickaxe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(CENTERL_AXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "centerl_axe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(CENTERL_HOE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "centerl_hoe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(CENTERL_HELMET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "centerl_helmet"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(CENTERL_CHESTPLATE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "centerl_chestplate"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(CENTERL_LEGGINGS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "centerl_leggings"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(CENTERL_BOOTS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "centerl_boots"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(PERMAFROST_SWORD, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "permafrost_sword"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(PERMAFROST_SHOVEL, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "permafrost_shovel"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(PERMAFROST_PICKAXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "permafrost_pickaxe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(PERMAFROST_AXE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "permafrost_axe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(PERMAFROST_HOE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "permafrost_hoe"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(PERMAFROST_HELMET, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "permafrost_helmet"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(PERMAFROST_CHESTPLATE, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "permafrost_chestplate"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(PERMAFROST_LEGGINGS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "permafrost_leggings"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(PERMAFROST_BOOTS, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "permafrost_boots"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TEA_SEED, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tea_seed"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(TEA_FLOWER, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "tea_flower"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(SILVER_APPLE, 1, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "silver_apple"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(RADEON, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "radeon_vii"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(RADEON, 1, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "radeon_pro_v340"), "inventory"));
        ModelLoader.setCustomModelResourceLocation(REFI_SWORD, 0, new ModelResourceLocation(new ResourceLocation(Variable.MODID, "refi_sword"), "inventory"));
    }
}
